In [7]:
import numpy as np
import time
size = 10_00_000

# python list
py_list = list(range(size))
start = time.time()
sq_py_list = [i**2 for i in py_list]
end = time.time()
print(end-start)

#numpy array
np_list = np.array(py_list)
start = time.time()
sq_np_list = np_list ** 2
end = time.time()
print(end-start)

0.12847018241882324
0.0038361549377441406


In [8]:
#creating Array from list
arr = np.array([1,2,3,4,5])
print(arr,arr.shape,arr.dtype)

arr2 = np.array([1,2,3,4,5,6,'string'])
print(arr2,arr2.shape,arr2.dtype)

arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D,arr_2D.shape,arr_2D.dtype)

[1 2 3 4 5] (5,) int64
['1' '2' '3' '4' '5' '6' 'string'] (7,) <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int64


In [22]:
#creating directly an np_array
a1 = np.zeros((3,3)) #default will give float values
print(a1)

a1 = np.zeros((3,3),dtype = "int64") # gives all 0 only int values
print(a1)

a2 = np.ones((4,4),dtype = "int64") # gives all 1 only int values
print(a2)

a3 = np.full((3,3),100) # fill 100 in 3x3 array
print(a3)

a4 = np.eye(4 , dtype="int64") # gives a identical matrix of 1 
print(a4)

a5 = np.arange(1,6) # in py same like range fun
print(a5)

a6 = np.linspace(1,1000,5,dtype="int64") # gives a linear space from 1 to 1000 into 5 parts
print(a6)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[1 2 3 4 5]
[   1  250  500  750 1000]


In [25]:
# properties of np array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [26]:
#properties on array
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2)) # it reshapes the size
print(reshaped,reshaped.shape)

flattened = arr.flatten() # makes into 1D array
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [35]:
#array Indexing
arr1 = np.array([1,2,3,4,5,6])
print(arr1[3])
print(arr1[4])
print()

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0][0])
print(arr2[1][1])
print()

#fancy indexing
ind = [1,3,4]
print(arr1[ind])
print()

#boolean indexing : means based on condition it will print
print(arr1[arr1>3])
print(arr1[arr1<4])
print(arr1[arr1 %2 == 0])
print()

#slicing 
print(arr1[1:4])

4
5

1
5

[2 4 5]

[4 5 6]
[1 2 3]
[2 4 6]

[2 3 4]


In [40]:
#diff between copy ans view
arr = [1,2,3,4,5,6,7] 
sub_arr = arr[1:4] # it will make copy so it is slow 
sub_arr[0] = 200
print(arr)
print(sub_arr)
print()

np_arr = np.array([1,2,3,4,5,6,7])
np_sub_arr = np_arr[1:4] # it will give the view and if u change data here it will change in the view , so the real data will be changed
np_sub_arr[0] = 200
print(np_arr)
print(np_sub_arr)
print()

# if we use .copy() fun then the copy is created from np array and there will be no change in the real data
np_arr = np.array([1,2,3,4,5,6,7])
np_sub_arr = np_arr[1:4].copy()
np_sub_arr[0] = 200
print(np_arr)
print(np_sub_arr)
print()

[1, 2, 3, 4, 5, 6, 7]
[200, 3, 4]

[  1 200   3   4   5   6   7]
[200   3   4]

[1 2 3 4 5 6 7]
[200   3   4]



In [41]:
#Common Data Types
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes)        # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)


# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

int64
float64
<U5
40
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


In [53]:
#axes in multidimentional
ar = np.array([1,2,3,4,5,5,6,7]) # in 1D there will be only 1 axes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr) # in 2D array there will be 2 axes, 0 : deals with row and operations are done by vertical that means column, 
# 1 : deals with column and operations are done by horizontal
sum = np.sum(arr)
print(sum)

#2D Arrays
#sum using axis 0 will be all verticals , that means those are columns
sum2 = np.sum(arr,axis = 0)
print(sum2)

#sum using axis 1 will be all horizontal , that means those are columns
sum3 = np.sum(arr,axis = 1)
print(sum3)


# 3D Array
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)
print(arr3D[:,0,:])
print(arr3D[:,:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [60]:
#vectorization and broadCasting

#vec
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)
print(arr1 ** 2)
print()

#broadcasting can be done only when the size matches and if one of them is 1 shape but not in multiple shape
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[6,7,8,9,10],[6,7,8,9,10]])
print(arr1+arr2) # we can do this 

# arr2 = np.array([[6,7,8,9,10],[6,7,8,9,10]])
# arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10]])
# print(arr1+arr2) # we cannot do this 

[ 7  9 11 13 15]
[ 1  4  9 16 25]

[[ 7  9 11 13 15]
 [ 7  9 11 13 15]]


In [61]:
#Normalize
arr = np.array([[1,2],[3,4]])
arr_mean = np.mean(arr)
arr_std = np.std(arr)
normalized_arr = (arr-arr_mean)/arr_std
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [63]:
#Mathematical functions
#agression
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.var(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))


45
362880
1
9
0
8
6.666666666666667
2.581988897471611
5.0
5.0


In [74]:
#power functions
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))
print()


#logarithms
print(np.log(arr))
print(np.log2(arr))
print(np.log10(arr))
print(np.exp(arr))
print()

#rounding
arr1 = np.array([1,2.5,3,4,5]) # from .0 to .49 gives below value and from .5 to .99 givesupper value
print(np.round(arr1))
print(np.ceil(arr1))
print(np.floor(arr1))
print(np.trunc(arr1))
print()

#Extra
a = np.array([2,3,2132,4,34,9,2,22,1,2,12,2,5435,-324,-34,4,3])
print(np.unique(a))
print(np.sort(a))
print(np.abs(a))
print()

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

[1. 2. 3. 4. 5.]
[1. 3. 3. 4. 5.]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]

[-324  -34    1    2    3    4    9   12   22   34 2132 5435]
[-324  -34    1    2    2    2    2    3    3    4    4    9   12   22
   34 2132 5435]
[   2    3 2132    4   34    9    2   22    1    2   12    2 5435  324
   34    4    3]

